// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cleanup} from '../models';
import {scanner} from '../models';
import {forecast} from '../models';
import {main} from '../models';

export function AddSSHHost(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function BrowseFolder():Promise<string>;

export function CancelScan():Promise<void>;

export function DeleteSSHHost(arg1:number):Promise<void>;

export function DryRunCleanup(arg1:Array<string>):Promise<cleanup.DryRunResult>;

export function EditSSHHost(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string):Promise<void>;

export function GenerateAIRecommendation(arg1:string,arg2:Array<scanner.FileInfo>):Promise<string>;

export function GetAIModels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetAIProviders():Promise<Array<Record<string, any>>>;

export function GetRecentScans():Promise<Array<Record<string, any>>>;

export function GetSSHHosts():Promise<Array<Record<string, any>>>;

export function GetScanRules():Promise<string>;

export function GetStorageForecast(arg1:string):Promise<forecast.ForecastResult>;

export function GetTheme():Promise<string>;

export function SafeDeleteFiles(arg1:Array<string>,arg2:boolean):Promise<void>;

export function SaveAIProvider(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SaveScanRules(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function StartScan(arg1:string,arg2:number,arg3:string):Promise<string>;

export function TestAIProviderConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<main.ConnectionResult>;
