// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSSHHost(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddSSHHost'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function DeleteSSHHost(arg1) {
  return window['go']['main']['App']['DeleteSSHHost'](arg1);
}

export function DryRunCleanup(arg1) {
  return window['go']['main']['App']['DryRunCleanup'](arg1);
}

export function EditSSHHost(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EditSSHHost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GenerateAIRecommendation(arg1, arg2) {
  return window['go']['main']['App']['GenerateAIRecommendation'](arg1, arg2);
}

export function GetAIModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAIModels'](arg1, arg2, arg3);
}

export function GetAIProviders() {
  return window['go']['main']['App']['GetAIProviders']();
}

export function GetRecentScans() {
  return window['go']['main']['App']['GetRecentScans']();
}

export function GetSSHHosts() {
  return window['go']['main']['App']['GetSSHHosts']();
}

export function GetScanRules() {
  return window['go']['main']['App']['GetScanRules']();
}

export function GetStorageForecast(arg1) {
  return window['go']['main']['App']['GetStorageForecast'](arg1);
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function SafeDeleteFiles(arg1, arg2) {
  return window['go']['main']['App']['SafeDeleteFiles'](arg1, arg2);
}

export function SaveAIProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAIProvider'](arg1, arg2, arg3, arg4);
}

export function SaveScanRules(arg1) {
  return window['go']['main']['App']['SaveScanRules'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function StartScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3);
}

export function TestAIProviderConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestAIProviderConnection'](arg1, arg2, arg3, arg4, arg5);
}
